language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'

before_install:
  - composer require satooshi/php-coveralls

before_script:
  - composer self-update
  - composer install --prefer-source --dev
  - docker run -p 9000:9000 -p 8123:8123 -d --name some-clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server

script: vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
  - php vendor/bin/php-coveralls -v

notifications:
  on_success: never
  on_failure: always
